### ISSUE TITLE
Homescreen

### ISSUE THREAD

**Issue by Alkawi** [Alkawi/capstone-project#2]
## Value proposition
**As a** user
**I need** a way to add concerts
**in order to** have an overview of all upcoming concerts

## Description
<img height=500 src=https://user-images.githubusercontent.com/75093518/142772433-8976c643-6218-4f6b-ace2-971a3b29b533.png />

## Acceptance criteria
- [x] all inputs fields except for "Support" are `required`
- [x] "Number of tickets" input has to be an integer
- [x] "Date" input has to be date
- [x] Max. 100 characters for "Main Act", "Support" and "Location"
- [x] the list of concerts should scroll vertically on overflow
- [x] concert card should display all entered data
- [x] "Add concerts" button should display input form
- [x] "Save and go back" button should go back to home
- [x] "Upcoming" should display number of concerts
- [x] data should be persistent

## Tasks
- [x] Create README
- [x] Button component
- [x] Form component
- [x] Card component
- [x] Add localStorage
- [x] Upcoming component
- [x] Integrate components into app
- [x] Setup deployment
