### ISSUE TITLE
User profile

### ISSUE THREAD

**Issue by Alkawi** [Alkawi/capstone-project#24]
## Value proposition
**As a** user
**I need** a way to create and log in to an account
**in order to** have my data synced with other devices

## Description
<img height=500 src=https://user-images.githubusercontent.com/75093518/143871510-097ae9fe-b9c7-4a9f-a00d-35a1fd2db41b.png />

## Acceptance criteria
- [x] username input is type string
- [x] password input is type password
- [x] username & password inputs are required
- [x] min length for password input is 8 characters
- [ ] Cookie has to save logged in user until logged out
- [x] User & Concerts data are stored in MongoDB
- [x] Password is not stored in plain text
- [x] Username has to be unique 
- [x] User can update password
- [ ] Total number of concerts are displayed on user profile page

## Tasks
- [x] User Form component
- [x] Move Add Concerts form to own page
- [x] Add MongoDB
- [x] Create Api
- [x] Registration page
- [x] Registration logic
- [x] Login page
- [x] Login logic
- [ ] User Profile page
- [ ] Navigation component
